In [1]:
import numpy as np

In [5]:
# array creation
a = np.array([1, 2, 3])  # 1d array
b = np.array([[1, 2], [3, 4]])  # 2d array
c = np.zeros((3, 3))  # 3 * 3 arrays of zeroes   
d = np.ones((2, 2))  # 2 * 2 arrays of ones
e = np.arange(0, 10, 2)  # (start, end, steps) - create an array like this

print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]


In [8]:
# array operations
print(a + 1)  # adding 1 to each element
print(a * 2)  # multiplying each element by 2
print(a ** 2)  # square each element
np.sqrt(a)  # square root of each element

[2 3 4]
[2 4 6]
[1 4 9]


array([1.        , 1.41421356, 1.73205081])

In [9]:
# array indexing and slicing
print(a[0])  # 1 st element
print(b[0, 1])  # element at row 0 and column 1
print(a[1:])  # elements from index 1 onwards
print(b[:, 1])  # every row but 2nd column

1
2
[2 3]
[2 4]


In [10]:
# array shape manipulation
print(a.reshape(3, 1))  # reshape to 3 * 1 array
print(b.flatten())  # flatten 2d array to 1d array

[[1]
 [2]
 [3]]
[1 2 3 4]


In [1]:
# mathematical operations
print(np.sum(a))  # sum of all elements
print(np.mean(a))  # mean of all elements
print(np.max(a))  # max of all elements
print(np.min(a))  # min of all elements
print(np.median(a))
print(np.sqrt(a))


NameError: name 'np' is not defined

In [12]:
# linear algebra
print(np.dot(a, a))  # dot product 
print(np.linalg.inv(b))  # inverse of a matrix
print(np.linalg.eig(b))  # eigen values and eigen vectors

14
[[-2.   1. ]
 [ 1.5 -0.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [18]:
# broadcasting
a += np.array([10, 20, 30])
print(a)

[ 41  82 123]


In [19]:
# random number generation
print(np.random.rand(3, 3))  # 3 * 3 array of random numbers between 0 and 1
print(np.random.randn(3, 3))  # 3 * 3 array of random numbers from standard normal distribution

[[0.11512604 0.99190553 0.0047844 ]
 [0.26960447 0.7302894  0.62799881]
 [0.71770603 0.80607675 0.04011463]]
[[ 1.7539608  -0.07387442 -0.52507189]
 [ 0.14927733  0.93734651 -1.06361014]
 [ 1.13980298 -2.12267527 -1.33419005]]
